version: '2'

services:
  website:
    # build: .
    image: asia-east1-docker.pkg.dev/pirate-gemini-8394/prac/flask-app:latest
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "snakeeyes.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/snakeeyes'
    ports:
      - '8000:8000'
